### PR TITLE
my color :D

### PR DESCRIPTION
**Pull request by MyNameNoneOfYourBusiness**

### CODE REVIEW

**Comment by PAPERPANKS** [comment]
@MyNameNoneOfYourBusiness use capital form for `<hexcolorcode> `

**Comment by MyNameNoneOfYourBusiness** [comment]
Okay fixed it :D

**Comment by PAPERPANKS** [comment]
good work. now star repo if you like my work

**Comment by MyNameNoneOfYourBusiness** [comment]
Sure :D

**Pull request merged**
